apiVersion: v1
baseDomain: com
compute:
- hyperthreading: Enabled
  name: worker
  replicas: 0
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3
metadata:
  name: mwocp
networking:
  serviceNetwork:
  - 172.30.0.0/16
  clusterNetwork:
  - cidr: 172.40.0.0/16
    hostPrefix: 24
  machineCIDR: 172.50.0.0/16
  networkType: OpenShiftSDN
platform:
  none: {}
imageContentSources:
- mirrors:
  - registry.mwocp.com:5000/ocp43/release
  source: quay.io/openshift-release-dev/ocp-release
- mirrors:
  - registry.mwocp.com:5000/ocp43/release
  source: quay.io/openshift-release-dev/ocp-v4.0-art-dev  
additionalTrustBundle: |
  -----BEGIN CERTIFICATE-----
  MIIDaDCCAlACCQDVaynFZbrofzANBgkqhkiG9w0BAQsFADB2MQswCQYDVQQGEwJL
  UjEOMAwGA1UECAwFU2VvdWwxDjAMBgNVBAcMBVNlb3VsMRIwEAYDVQQKDAlyb2Nr
  UExBQ0UxFjAUBgNVBAsMDUlUIERlcGFydG1lbnQxGzAZBgNVBAMMEnJlZ2lzdHJ5
  Lm13b2NwLmNvbTAeFw0yMDA0MjMxNDIyMzVaFw0yMTA0MjMxNDIyMzVaMHYxCzAJ
  BgNVBAYTAktSMQ4wDAYDVQQIDAVTZW91bDEOMAwGA1UEBwwFU2VvdWwxEjAQBgNV
  BAoMCXJvY2tQTEFDRTEWMBQGA1UECwwNSVQgRGVwYXJ0bWVudDEbMBkGA1UEAwwS
  cmVnaXN0cnkubXdvY3AuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKC
  AQEArnif35livrZvArpgWIII5eojeGnd9WPpfiaDwy9jFotukr/K/Mljy9sTtGzG
  0b5tBEJKk7kOpgBqQFR5l8v7QVo4Bj72+2xQbm2BUXuiRZtI5YHyf+32MwsGqP/w
  1jb7IGe5EntFSfIB3A8OtQq13PsYM4RN4ghpdx6HaT4M3aeivXPjuaLBEBfillVD
  ojTUKT8u/jeBTvpnl/fTWtlGe3X2lWD7Km2efnLsh8rPAppVOJxCPBjGtWh/SUL5
  xb1qQvPliuAJGNluhQ6edOevKCQIU3ZuyHdFzIL/Dw9csa996bnMM4sxHyW+lZ3n
  B7N8CMMVfpKl1eMs4n5UALzDQwIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQBnbgPm
  yaG3lovyxc1VLJN7zt14+Wo0jRUWrr5EsxVhO0P0jksMLEOGHElQU9zDbgJ+dt2c
  yFMujpJIbfJi4Kr7FRLNbU6dUuSJB60oxySQaU6pkHo/VWkYez5pe4N/q6mWLrwa
  jm2HFcpJ2pE6gKz2KxfR7OEabfqVn5gqc8HDghMIkCr0D26z6Vx6cepXfmUVnmRg
  nGKg7wJrbZVbbUbSXFdHD4tX45nrNCC+dMgWp0sdeUlIOC60eX/DaT5mTWd5vWYW
  JT98mFl/6LstXV/H2LVJF9O9EzJ0DG/yMiAen+Avg/20CrPcq8ycFLjGTOo/IiMV
  xp3PeOC6TRJKONXb
  -----END CERTIFICATE----- 
pullSecret: '{"auths":{"registry.mwocp.com:5000":{"auth":"YWRtaW46cnBsaW51eA==","email":"mwsong@rockplace.co.kr"}}}'
sshKey: |
  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3KhYWwE3F2OxiLplD1fqD0XpeEfEpZoJy8WEmi7RakAsDWPXBVrpwcXhIlaDm4VQCIGCUqxfEKR5jePz9yD7XM9okfXtHcwbkMBfhfO2oVEhs/e/P6EzuY8lHeUk5T/FqCCCGWCA8ktXQbOrzQ3qJion5ppQZqSV0fpuZv4cwf98jbMIFcMfbUNHGXFnsJWW0/7/vrQRa4Q4pDgEMIbxD2GNUg7iuvKGt4h7qNCvbw5Nk8SwmCR+Rw2yGG8BVQaZbSGhjCiU9Y0v08r0HaxCOLLt0aAOCaPXmsMGQAfiy5KEY+qUG/hzTho460o84RVkztDtpr30x4wvRyACwc9A5 ssong@gram
